#!/bin/bash
#PBS -N moose_job
#PBS -j oe
#PBS -k doe
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=48:mpiprocs=48
#PBS -P hpc

module use /home/behnpa/modulefiles
module load git
module load use.moose moose-mpich

cd /home/behnpa/projects/convection_loop/problems/3d/cask
mpiexec -n 48 ../../../convection_loop-opt -i child_fuel_rod.i T_cold=293 h_interface=20 mesh_path='mesh/mesh14' --split-mesh 67 --split-file fuel_rod_3d.cpr
