#!/bin/bash
#PBS -N moose_job
#PBS -j oe
#PBS -k doe
#PBS -l walltime=02:00:00
#PBS -l select=20:ncpus=48:mpiprocs=48
#PBS -P hpc

module use /home/behnpa/modulefiles
module load git
module load use.moose moose-mpich

cd /home/behnpa/projects/convection_loop/problems/3d/cask
mpiexec -n 960 ../../../convection_loop-opt -i parent_cask.i --distributed-mesh --split-mesh 10080 --split-file quarter_cask_3d.cpr
